### ISSUE TITLE
AWS returns error

### ISSUE THREAD

**Issue by tvansteelandt** [Upplication/gulp-elasticbeanstalk-deploy#4]
The gulp command exits with an error.
Deploy succeeded though.

> InvalidRequestException: DescribeEnvironmentHealth is not supported.
> [error.txt](https://github.com/Upplication/gulp-elasticbeanstalk-deploy/files/555519/error.txt)

**Comment by Souler** [comment]
This is probably caused because your **Health Reporting** type is set to _Basic_ on the ElasticBeanstalk instance. You can change it to _Enhanced_ without incurring in extra costs and will avoid this problem.

[Source](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElasticBeanstalk.html#describeEnvironmentHealth-property)

I'm leaving this issue open, because I think it would be more user-friendly to handle this case with a nice error message :)
